/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Dao.ChiTietHoaDonDao;
import Dao.HoaDonDao;
import Dao.KhachHangDao;
import Dao.PhongDao;
import Pojo.ChiTietHoaDon;
import Pojo.KhachHang;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 84862
 */
public class FormThanhToan extends javax.swing.JFrame {

    formHoaDon frmHd;
    ChiTietHoaDonDao handleCTHoaDon= new ChiTietHoaDonDao();
    HoaDonDao handleHoaDon=new HoaDonDao();
    /**
     * Creates new form FormThanhToan
     */
    KhachHangDao handleKhachHang= new KhachHangDao();
    public FormThanhToan(formHoaDon hd) {
        initComponents();
        frmHd=hd;
        init();
        init_Table();
    }
    
    public void init_Table()
    {
        String selectedMaHD = frmHd.txt_MaHD.getText().toString();
        if (selectedMaHD != null) {
            ArrayList<ChiTietHoaDon> ds = handleCTHoaDon.layDSChiTietHoaDonTheoMaHD(Integer.parseInt(selectedMaHD));
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("MaCTHD");
            dtm.addColumn("Mã phòng");
            dtm.addColumn("Thời gian đặt");
            dtm.addColumn("Thời gian trả");
            dtm.setNumRows(ds.size());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                
            for(int i = 0; i < ds.size(); i++)
            {
                ChiTietHoaDon cthd = ds.get(i);
                dtm.setValueAt(cthd.getMaCTHD(), i, 0);
                dtm.setValueAt(cthd.getMaPhong(), i, 1);

                String formattedTgDat = dateFormat.format(cthd.getTgDat());
                dtm.setValueAt(formattedTgDat, i, 2);

                String formattedTgTra = dateFormat.format(cthd.getTgTra());
                dtm.setValueAt(formattedTgTra, i, 3);
            }
            tb_CTHD.setModel(dtm);
        }
    }
    public void init()
    {
        LocalDate ngayHienTai = LocalDate.now();
        DateTimeFormatter dinhDangNgay = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String text = ngayHienTai.format(dinhDangNgay);
        txt_NgayHienTai.setText(text);
        txt_TongTien.setText(frmHd.txt_TongTien.getText());
        KhachHang khtemp= handleKhachHang.layKhachHangTheoMa(frmHd.cbx_MaKH.getSelectedItem().toString());
        txt_CMND.setText(khtemp.getSoCMND());
        txt_GioiTinh.setText(khtemp.getGioiTinh());
        txt_SDT.setText(khtemp.getSDT());
        txt_TenKH.setText(khtemp.getTenKH());
        txt_MaHD.setText(String.valueOf(frmHd.txt_MaHD.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_NgayHienTai = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JLabel();
        txt_CMND = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JLabel();
        txt_GioiTinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_CTHD = new javax.swing.JTable();
        btn_ThanhToan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("HÓA ĐƠN THANH TOÁN TIỀN PHÒNG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Ngày");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Mã hóa đơn :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Tên khách hàng :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 5));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Số CMND :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("SDT :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Giới tính :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 800, 5));

        txt_NgayHienTai.setText("jLabel8");
        getContentPane().add(txt_NgayHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        txt_MaHD.setText("jLabel9");
        getContentPane().add(txt_MaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        txt_TenKH.setText("jLabel8");
        getContentPane().add(txt_TenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        txt_CMND.setText("jLabel9");
        getContentPane().add(txt_CMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        txt_SDT.setText("jLabel10");
        getContentPane().add(txt_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        txt_GioiTinh.setText("jLabel11");
        getContentPane().add(txt_GioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        tb_CTHD.setForeground(new java.awt.Color(153, 0, 0));
        tb_CTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_CTHD.setRowHeight(40);
        tb_CTHD.setSelectionBackground(new java.awt.Color(153, 0, 0));
        tb_CTHD.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tb_CTHD);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 800, 170));

        btn_ThanhToan.setBackground(new java.awt.Color(153, 0, 0));
        btn_ThanhToan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThanhToan.setText("Thanh Toán");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Tổng tiền :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        txt_TongTien.setText("jLabel9");
        getContentPane().add(txt_TongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
        handleHoaDon.updateStatePhong(Integer.parseInt(txt_MaHD.getText().toString()));
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThanhToan(new formHoaDon()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_CTHD;
    private javax.swing.JLabel txt_CMND;
    private javax.swing.JLabel txt_GioiTinh;
    private javax.swing.JLabel txt_MaHD;
    private javax.swing.JLabel txt_NgayHienTai;
    private javax.swing.JLabel txt_SDT;
    private javax.swing.JLabel txt_TenKH;
    private javax.swing.JLabel txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
