/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui;

import Dao.ChiTietHoaDonDao;

import Dao.HoaDonDao;
import Dao.KhachHangDao;
import Pojo.HoaDon;
import Dao.NhanVienDao;
import Pojo.ChiTietHoaDon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author AD
 */
public class formHoaDon extends javax.swing.JPanel {
    /**
     * Creates new form formHoaDoan
     */

    KhachHangDao handleKhachHang= new KhachHangDao();
    NhanVienDao handleNhanVien= new NhanVienDao();
    HoaDonDao handleHoaDon= new HoaDonDao();
    ChiTietHoaDonDao handleCTHoaDon= new ChiTietHoaDonDao();
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    public formHoaDon() {
        initComponents();

        hienThiHoaDon();
        hienThiCTHoaDon();
    
        tbl_HoaDon.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                tbl_HoaDonMouseClicked(evt);
            }
        });
    }

    public void hienThiHoaDon()
    {
        ArrayList<String> dsNhanVien = NhanVienDao.layDSNhanVien();
        cbx_MaNV.addItem("");
        for(String maNV:dsNhanVien)
        {
            cbx_MaNV.addItem(maNV);
        }
        ArrayList<String> dsKhachHang = KhachHangDao.layDSMaKH();
        cbx_MaKH.addItem("");
        for(String maKH:dsKhachHang)
        {
            cbx_MaKH.addItem(maKH);
        }
        ArrayList<HoaDon> ds = handleHoaDon.layDSHoaDon();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã hóa đơn");
        dtm.addColumn("Mã nhân viên");
        dtm.addColumn("Mã khách hàng");
        dtm.addColumn("Phí phát sinh");
        dtm.addColumn("Tổng tiền");
        dtm.addColumn("Thanh toán");
        dtm.addColumn("Ghi chú");
        dtm.setNumRows(ds.size());
        for(int i=0; i<ds.size(); i++)
        {
            HoaDon hd = ds.get(i);
            dtm.setValueAt(hd.getMaHD(), i, 0);
            dtm.setValueAt(hd.getMaNV(), i, 1);
            dtm.setValueAt(hd.getMaKH(), i, 2);
            dtm.setValueAt(hd.getPhiPhatSinh(), i, 3);
            dtm.setValueAt(hd.getTongTien(), i, 4);
            dtm.setValueAt(hd.getThanhToan(), i, 5);
            dtm.setValueAt(hd.getGhiChu(), i, 6);  
        }
        tbl_HoaDon.setModel(dtm);
    }
        
    public void hienThiCTHoaDon()
    {           
        ArrayList<Integer> dsHoaDon = HoaDonDao.layDSMaHD();        
        //cbo_MaHD.addItem("");
        for(int maHD : dsHoaDon)
        {
            cbo_MaHD.addItem(String.valueOf(maHD));
        }        
        ArrayList<ChiTietHoaDon> ds = handleCTHoaDon.layDSChiTietHoaDon();
        DefaultTableModel dtm = new DefaultTableModel();
        //DefaultTableModel dtm = (DefaultTableModel) tb_ChiTietHoaDon.getModel();
        dtm.setRowCount(0);
        
        dtm.addColumn("Mã chi tiết hóa đơn");
        dtm.addColumn("Mã hóa đơn");
        dtm.addColumn("Mã phòng");
        dtm.addColumn("Thời gian đặt");
        dtm.addColumn("Thời gian trả");
        dtm.setNumRows(ds.size());        
        
        for(int i=0; i<ds.size(); i++)
        {
            ChiTietHoaDon cthd = ds.get(i);
            dtm.setValueAt(cthd.getMaCTHD(), i, 0);
            dtm.setValueAt(cthd.getMaHD(), i, 1);
            dtm.setValueAt(cthd.getMaPhong(), i, 2);
            dtm.setValueAt(dateFormat.format(cthd.getTgDat()), i, 3);
            dtm.setValueAt(dateFormat.format(cthd.getTgTra()), i, 4); 
        }
        tb_ChiTietHoaDon.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbx_MaKH = new javax.swing.JComboBox<>();
        txt_MaHD = new javax.swing.JTextField();
        btn_Xoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_LamLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();
        txt_PhiPhatSinh = new javax.swing.JTextField();
        txt_GhiChu = new javax.swing.JTextField();
        txt_TimKiem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbx_MaNV = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_Sua = new javax.swing.JButton();
        txt_ThanhToan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_ThanhToan = new javax.swing.JButton();
        btn_ThemHD = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_ChiTietHoaDon = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_MaCTHD = new javax.swing.JTextField();
        txt_MaPhong = new javax.swing.JTextField();
        cbo_MaHD = new javax.swing.JComboBox<>();
        btn_XoaCTHD = new javax.swing.JButton();
        btn_SuaCTHD = new javax.swing.JButton();
        btn_LamLaiCTHD = new javax.swing.JButton();
        txt_ThoiGianTra = new javax.swing.JFormattedTextField();
        txt_ThoiGianDat = new javax.swing.JFormattedTextField();
        btn_ThemCTHD = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1370, 670));
        setPreferredSize(new java.awt.Dimension(1370, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(cbx_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, 30));

        txt_MaHD.setEnabled(false);
        jPanel1.add(txt_MaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 160, 30));

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 0));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Ghi chú");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btn_LamLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/reset_1.png"))); // NOI18N
        btn_LamLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamLaiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LamLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 80, 30));

        tbl_HoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_HoaDon.setForeground(new java.awt.Color(153, 0, 0));
        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_HoaDon.setGridColor(new java.awt.Color(255, 153, 0));
        tbl_HoaDon.setMinimumSize(new java.awt.Dimension(300, 320));
        tbl_HoaDon.setRowHeight(80);
        tbl_HoaDon.setSelectionBackground(new java.awt.Color(153, 0, 0));
        tbl_HoaDon.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_HoaDon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 730, 410));
        jPanel1.add(txt_PhiPhatSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 92, 160, 30));
        jPanel1.add(txt_GhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 510, 30));
        jPanel1.add(txt_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 380, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Phí phát sinh");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("Tìm kiếm:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Tổng tiền");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));
        jPanel1.add(txt_TongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Thanh toán");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jPanel1.add(cbx_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Mã nhân viên");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        btn_Sua.setBackground(new java.awt.Color(0, 255, 255));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 120, 30));
        jPanel1.add(txt_ThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Mã hóa đơn");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("HÓA ĐƠN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Mã khách hàng");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/search.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, 30));

        btn_ThanhToan.setBackground(new java.awt.Color(0, 255, 0));
        btn_ThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThanhToan.setText("Thanh Toán");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 30));

        btn_ThemHD.setBackground(new java.awt.Color(0, 153, 255));
        btn_ThemHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemHD.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemHD.setText("Thêm");
        btn_ThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemHDActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ThemHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 130, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("CHI TIẾT HÓA ĐƠN");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        tb_ChiTietHoaDon.setForeground(new java.awt.Color(153, 0, 0));
        tb_ChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MaCTHD", "MaHD", "Mã Phòng", "Thời gian đặt", "Thời gian trả"
            }
        ));
        tb_ChiTietHoaDon.setMinimumSize(new java.awt.Dimension(375, 320));
        tb_ChiTietHoaDon.setRowHeight(80);
        tb_ChiTietHoaDon.setSelectionBackground(new java.awt.Color(153, 0, 0));
        tb_ChiTietHoaDon.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tb_ChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ChiTietHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_ChiTietHoaDon);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 640, 410));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Mã hóa đơn");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("Mã chi tiết hóa đơn");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setText("Mã phòng");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setText("Thời gian đặt");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 0));
        jLabel15.setText("Thời gian trả");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        txt_MaCTHD.setEnabled(false);
        jPanel2.add(txt_MaCTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 130, 30));
        jPanel2.add(txt_MaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, 30));

        cbo_MaHD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_MaHDItemStateChanged(evt);
            }
        });
        cbo_MaHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbo_MaHDMouseClicked(evt);
            }
        });
        jPanel2.add(cbo_MaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 150, 30));

        btn_XoaCTHD.setBackground(new java.awt.Color(255, 0, 0));
        btn_XoaCTHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaCTHD.setForeground(new java.awt.Color(255, 255, 255));
        btn_XoaCTHD.setText("Xóa");
        btn_XoaCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaCTHDActionPerformed(evt);
            }
        });
        jPanel2.add(btn_XoaCTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, 30));

        btn_SuaCTHD.setBackground(new java.awt.Color(0, 255, 255));
        btn_SuaCTHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SuaCTHD.setForeground(new java.awt.Color(255, 255, 255));
        btn_SuaCTHD.setText("Sửa");
        btn_SuaCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaCTHDActionPerformed(evt);
            }
        });
        jPanel2.add(btn_SuaCTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 90, 30));

        btn_LamLaiCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/reset_1.png"))); // NOI18N
        btn_LamLaiCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamLaiCTHDActionPerformed(evt);
            }
        });
        jPanel2.add(btn_LamLaiCTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 70, 30));

        txt_ThoiGianTra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        jPanel2.add(txt_ThoiGianTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 142, 170, 30));

        txt_ThoiGianDat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        jPanel2.add(txt_ThoiGianDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 102, 150, 30));

        btn_ThemCTHD.setBackground(new java.awt.Color(51, 255, 51));
        btn_ThemCTHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemCTHD.setText("Thêm");
        btn_ThemCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemCTHDActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ThemCTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 670, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
        
       int selectedRow = tbl_HoaDon.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy dữ liệu từ bảng
            String ghiChu = tbl_HoaDon.getValueAt(selectedRow, 6).toString();
            if(!ghiChu.equals("đã thanh toán"))
            {
                FormThanhToan temp= new FormThanhToan(this);
                temp.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Hóa đơn này đã thanh toán");
            }
        }
       
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void btn_LamLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamLaiActionPerformed
        // TODO add your handling code here:
        txt_GhiChu.setText("");
        txt_MaHD.setText("");
        txt_PhiPhatSinh.setText("");
        cbx_MaNV.setSelectedIndex(-1);
        cbx_MaKH.setSelectedIndex(-1);
        txt_ThanhToan.setText("");
        txt_TongTien.setText("");
    }//GEN-LAST:event_btn_LamLaiActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        int maHD = Integer.parseInt(txt_MaHD.getText());
        int confirmed = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa lớp này không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            boolean success = handleHoaDon.xoaHoaDon(maHD);
            if (success) {
                // Thông báo thành công
                JOptionPane.showMessageDialog(this, "Xóa hóa đơn thành công!");
                // Cập nhật lại danh sách trên giao diện
                hienThiHoaDon();
            } else {
                // Thông báo thất bại
                JOptionPane.showMessageDialog(this, "Xóa hóa đơn thất bại!");
            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        HoaDon hd = new HoaDon();
        int maHD = Integer.parseInt(txt_MaHD.getText());
        hd.setMaHD(maHD);

        int maNV = handleNhanVien.layidNhanVienTheoTen((String) cbx_MaNV.getSelectedItem());
        hd.setMaNV(maNV);
        
        int maKH = handleKhachHang.layidKhachHangTheoTen((String) cbx_MaKH.getSelectedItem());
        hd.setMaKH(maKH);
        
        BigDecimal phiPhatSinh = new BigDecimal(txt_PhiPhatSinh.getText());
        BigDecimal thanhToan = new BigDecimal(txt_ThanhToan.getText());
        BigDecimal tongTien = new BigDecimal(txt_TongTien.getText());

        hd.setPhiPhatSinh(phiPhatSinh);
        hd.setThanhToan(thanhToan);
        hd.setTongTien(tongTien);
        hd.setGhiChu(txt_GhiChu.getText());

        boolean success = handleHoaDon.capNhatHoaDon(hd);
        if (success) {
            // Thông báo thành công
            JOptionPane.showMessageDialog(this, "Cập nhật hóa đơn thành công!");
            // Cập nhật lại danh sách sách trên giao diện
            hienThiHoaDon();
        } else {
            // Thông báo thất bại
            JOptionPane.showMessageDialog(this, "Cập nhật hóa đơn thất bại!");
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaCTHDActionPerformed
        int maCTHD = Integer.parseInt(txt_MaCTHD.getText());
        int confirmed = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa lớp này không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            boolean success = ChiTietHoaDonDao.xoaChiTietHoaDon(maCTHD);
            if (success) {
                // Thông báo thành công
                JOptionPane.showMessageDialog(this, "Xóa chi tiết hóa đơn thành công!");
                // Cập nhật lại danh sách trên giao diện
                hienThiCTHoaDon();
            } else {
                // Thông báo thất bại
                JOptionPane.showMessageDialog(this, "Xóa chi tiết hóa đơn thất bại!");
            }
        }
    }//GEN-LAST:event_btn_XoaCTHDActionPerformed

    private void btn_SuaCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaCTHDActionPerformed
        // TODO add your handling code here:
        ChiTietHoaDon cthd = new ChiTietHoaDon();
        int maPhong = Integer.parseInt(txt_MaPhong.getText());
        cthd.setMaPhong(maPhong);        
        
        try {
            // Chuyển đổi thành đối tượng Date
            Date thoiGianDat = dateFormat.parse(txt_ThoiGianDat.getText());
            java.sql.Date sqlTgDat= new java.sql.Date(thoiGianDat.getTime());
            cthd.setTgDat(sqlTgDat);
             
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Định dạng ngày đặt không hợp lệ!");
            return; // Dừng lại nếu có lỗi
        }
        
        try {
            // Chuyển đổi thành đối tượng Date
            Date thoiGianTra = dateFormat.parse(txt_ThoiGianTra.getText());
            java.sql.Date sqlTgTra= new java.sql.Date(thoiGianTra.getTime());
            cthd.setTgTra(sqlTgTra);
             
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Định dạng ngày đặt không hợp lệ!");
            return; // Dừng lại nếu có lỗi
        }
        String maHDStr = cbo_MaHD.getSelectedItem().toString();
        if (maHDStr == null || maHDStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã hóa đơn!");
            return;
        }
        int maHD = Integer.parseInt(maHDStr);
        cthd.setMaHD(maHD);
        
        cthd.setMaCTHD(Integer.parseInt(txt_MaCTHD.getText()));
        
        // Khởi tạo thông tin sách từ các trường dữ liệu trên giao diện

        // Gọi phương thức thêm sách từ lớp SachDAO
        boolean success = handleCTHoaDon.capNhatChiTietHD(cthd);
        if (success) {
            // Thông báo thành công
            JOptionPane.showMessageDialog(this, "Cập nhật hóa đơn thành công!");
            // Cập nhật lại danh sách sách trên giao diện
            hienThiCTHoaDon();
        } else {
            // Thông báo thất bại
            JOptionPane.showMessageDialog(this, "Cập nhật hóa đơn thất bại!");
        }
    }//GEN-LAST:event_btn_SuaCTHDActionPerformed

    private void btn_LamLaiCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamLaiCTHDActionPerformed
        // TODO add your handling code here:
        txt_MaPhong.setText("");
        txt_ThoiGianDat.setText("");
        txt_ThoiGianTra.setText("");
        txt_MaCTHD.setText("");
        cbo_MaHD.setSelectedIndex(-1);
    }//GEN-LAST:event_btn_LamLaiCTHDActionPerformed

    private void cbo_MaHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbo_MaHDMouseClicked
            
    }//GEN-LAST:event_cbo_MaHDMouseClicked

    private void tb_ChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ChiTietHoaDonMouseClicked
        int selectedRow = tb_ChiTietHoaDon.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy dữ liệu từ bảng
            String maCTHD = tb_ChiTietHoaDon.getValueAt(selectedRow, 0).toString();
            String maHD = tb_ChiTietHoaDon.getValueAt(selectedRow, 1).toString();
            String maPhong = tb_ChiTietHoaDon.getValueAt(selectedRow, 2).toString();
            String tgDatStr = tb_ChiTietHoaDon.getValueAt(selectedRow, 3).toString();
            String tgTraStr = tb_ChiTietHoaDon.getValueAt(selectedRow, 4).toString(); 

            // Convert String to java.util.Date
            
            Date tgDat = null;
            Date tgTra = null;
            try {
                tgDat = dateFormat.parse(tgDatStr);
                tgTra = dateFormat.parse(tgTraStr);
            } catch (ParseException e) {
                e.printStackTrace();
            }

            // Đổ dữ liệu vào các combobox và textbox tương ứng
            cbo_MaHD.setSelectedItem(maHD);
            txt_MaPhong.setText(maPhong);
            txt_MaCTHD.setText(maCTHD);
            //SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MM-yyyy");
            //txt_ThoiGianDat.setText(outputDateFormat.format(tgDat));
            //txt_ThoiGianTra.setText(outputDateFormat.format(tgTra));
            txt_ThoiGianDat.setText(dateFormat.format(tgDat));
            txt_ThoiGianTra.setText(dateFormat.format(tgTra));
        }

    }//GEN-LAST:event_tb_ChiTietHoaDonMouseClicked

    private void tbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbl_HoaDon.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy dữ liệu từ bảng
            String maHD = tbl_HoaDon.getValueAt(selectedRow, 0).toString();
            String maNV = tbl_HoaDon.getValueAt(selectedRow, 1).toString();
            String tenNV=handleNhanVien.SearchTenNhanVien(Integer.parseInt(maNV));
            String maKH = tbl_HoaDon.getValueAt(selectedRow, 2).toString();
            String tenKH=handleKhachHang.SearchTenKhachHang(Integer.parseInt(maKH));
            String phiPhatSinh = tbl_HoaDon.getValueAt(selectedRow, 3).toString();
            String tongTien = tbl_HoaDon.getValueAt(selectedRow, 4).toString();
            String thanhToan = tbl_HoaDon.getValueAt(selectedRow, 5).toString();
            String ghiChu = tbl_HoaDon.getValueAt(selectedRow, 6).toString();

            // Đổ dữ liệu vào các combobox và textbox tương ứng
            txt_MaHD.setText(maHD);
            cbx_MaNV.setSelectedItem(tenNV);
            cbx_MaKH.setSelectedItem(tenKH);
            txt_PhiPhatSinh.setText(phiPhatSinh);
            txt_TongTien.setText(tongTien);
            txt_ThanhToan.setText(thanhToan);
            txt_GhiChu.setText(ghiChu);
        }
    }//GEN-LAST:event_tbl_HoaDonMouseClicked

    private void cbo_MaHDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_MaHDItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
        String selectedMaHD = (String) evt.getItem();
        
        if(selectedMaHD == null || selectedMaHD.trim().isEmpty()){            
            hienThiCTHoaDon();
        }
        else{
            int maHD = Integer.parseInt(selectedMaHD);
            ArrayList<ChiTietHoaDon> ds = handleCTHoaDon.layDSChiTietHoaDonTheoMaHD(maHD);

            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Mã chi tiết hóa đơn");
            dtm.addColumn("Mã hóa đơn");
            dtm.addColumn("Mã phòng");
            dtm.addColumn("Thời gian đặt");
            dtm.addColumn("Thời gian trả");
            dtm.setNumRows(ds.size());

            for (int i = 0; i < ds.size(); i++) {
                ChiTietHoaDon cthd = ds.get(i);
                dtm.setValueAt(cthd.getMaCTHD(), i, 0);
                dtm.setValueAt(cthd.getMaHD(), i, 1);
                dtm.setValueAt(cthd.getMaPhong(), i, 2);                        

                dtm.setValueAt(dateFormat.format(cthd.getTgDat()), i, 3);                        

                dtm.setValueAt(dateFormat.format(cthd.getTgTra()), i, 4);
            }
            tb_ChiTietHoaDon.setModel(dtm);
            }
        }        
    }//GEN-LAST:event_cbo_MaHDItemStateChanged

    private void btn_ThemCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemCTHDActionPerformed
        // TODO add your handling code here:
        ChiTietHoaDon cthd = new ChiTietHoaDon();
        
        String selectedMaHD = (String) cbo_MaHD.getSelectedItem();
        cthd.setMaHD(Integer.parseInt(selectedMaHD));
        
        cthd.setMaPhong(Integer.parseInt(txt_MaPhong.getText()));
            try {
            String thoiGianDatStr = txt_ThoiGianDat.getText();
            String thoiGianTraStr = txt_ThoiGianTra.getText();

            java.sql.Date tgDat = null;
            if (!thoiGianDatStr.isEmpty()) {
                Date parsedDate = dateFormat.parse(thoiGianDatStr);
                tgDat = new java.sql.Date(parsedDate.getTime());
            }
            cthd.setTgDat(tgDat);

            java.sql.Date tgTra = null;
            if (!thoiGianTraStr.isEmpty()) {
                Date parsedDate = dateFormat.parse(thoiGianTraStr);
                tgTra = new java.sql.Date(parsedDate.getTime());
            }
            cthd.setTgTra(tgTra);

            boolean success = handleCTHoaDon.themChiTietHoaDon(cthd);
            if (success) {
                // Thông báo thành công
                JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thành công!");
                // Cập nhật lại danh sách trên giao diện
                hienThiCTHoaDon();
            } else {
                // Thông báo thất bại
                JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thất bại!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Định dạng ngày tháng không hợp lệ!");
        }
    }//GEN-LAST:event_btn_ThemCTHDActionPerformed

    private void btn_ThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemHDActionPerformed
        // TODO add your handling code here:
        HoaDon hd = new HoaDon();  
        
        int maNV = handleNhanVien.layidNhanVienTheoTen((String) cbx_MaNV.getSelectedItem());
        hd.setMaNV(maNV);
        
        
        int maKH = handleKhachHang.layidKhachHangTheoTen((String) cbx_MaKH.getSelectedItem());
        hd.setMaKH(maKH);

        // Gọi phương thức thêm sách từ lớp SachDAO
        boolean success = handleHoaDon.themHoaDon(hd);
        if (success) {
            // Thông báo thành công
            JOptionPane.showMessageDialog(this, "Thêm hóa đơn thành công!");
            // Cập nhật lại danh sách sách trên giao diện
            hienThiHoaDon();
        } else {
            // Thông báo thất bại
            JOptionPane.showMessageDialog(this, "Thêm hóa đơn thất bại!");
        }
    }//GEN-LAST:event_btn_ThemHDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamLai;
    private javax.swing.JButton btn_LamLaiCTHD;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_SuaCTHD;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JButton btn_ThemCTHD;
    private javax.swing.JButton btn_ThemHD;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XoaCTHD;
    private javax.swing.JComboBox<String> cbo_MaHD;
    public javax.swing.JComboBox<String> cbx_MaKH;
    private javax.swing.JComboBox<String> cbx_MaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_ChiTietHoaDon;
    private javax.swing.JTable tbl_HoaDon;
    private javax.swing.JTextField txt_GhiChu;
    private javax.swing.JTextField txt_MaCTHD;
    public javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_MaPhong;
    private javax.swing.JTextField txt_PhiPhatSinh;
    private javax.swing.JTextField txt_ThanhToan;
    private javax.swing.JFormattedTextField txt_ThoiGianDat;
    private javax.swing.JFormattedTextField txt_ThoiGianTra;
    private javax.swing.JTextField txt_TimKiem;
    public javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
